with open('templates/round2.html', 'r', encoding='utf-8') as f:
    html = f.read()
html = html.replace('<i class="fa-brands fa-java text-base"></i>', '{% if r2_track == "python" %}<i class="fa-brands fa-python text-base"></i>{% else %}<i class="fa-brands fa-java text-base"></i>{% endif %}')
html = html.replace('ROUND 2 &bull; JAVA DEBUGGING', 'ROUND 2 &bull; {{ r2_track|upper }} DEBUGGING')
html = html.replace('7 Intentional Bugs', 'Intentional Bugs')
html = html.replace('The 7 Error Distribution Categories:', 'Error Distribution Categories:')
html = html.replace('<li>Variable declaration / Type mismatch</li>', '<li>Variable declaration & Usage</li>')
html = html.replace('<li>Method signature / Visibility modifier</li>', '<li>Function / Method signature</li>')
html = html.replace('<li>Loop condition / Off-by-one boundary</li>', '<li>Loop condition and syntax</li>')
html = html.replace('<li>Array / Collection indexing &amp; mutation</li>', '<li>Collections &amp; Iterables</li>')
html = html.replace('<li>Java API usage / Exception handling</li>', '<li>Language-Specific Syntax (Colons, Indexing)</li>')
html = html.replace('Java Questions (1', '{{ r2_track|title }} Questions (1')
html = html.replace('14 Marks Each', '25 Marks Each')
html = html.replace('<i class="fa-brands fa-java text-red-400"></i>', '{% if r2_track == "python" %}<i class="fa-brands fa-python text-blue-400"></i>{% else %}<i class="fa-brands fa-java text-red-400"></i>{% endif %}')
html = html.replace('<span>Solution.java</span>', '<span>Solution.{{ "py" if r2_track == "python" else "java" }}</span>')
html = html.replace('(7 Errors to Resolve)', '')
html = html.replace('id="errors-fixed-counter" class="text-xs font-mono font-bold text-rose-400">0 / 7', 'id="errors-fixed-counter" class="text-xs font-mono font-bold text-rose-400">0 / -')
html = html.replace('resolved Java errors', 'resolved errors')
html = html.replace('Round 2: Java Debugging', 'Round 2: {{ r2_track|title }} Debugging')
html = html.replace('Bug Analysis &amp; Diagnostic Output', 'Bug Analysis &amp; Diagnostic Output ({{ r2_track|title }})')
with open('templates/round2.html', 'w', encoding='utf-8') as f:
    f.write(html)
